routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'AuthController@showFormLogin')->name('login');
Route::get('login', 'AuthController@showFormLogin')->name('login');
Route::post('login', 'AuthController@login');
Route::get('register', 'AuthController@showFormRegister')->name('register');
Route::post('register', 'AuthController@register');

Route::get('/soal1', function () {
    return view('soal1');
});
Route::group(['middleware' => 'auth'], function () {
    Route::get('home', function () {
        return view('welcome');
    })->name('home');
    Route::get('logout', 'AuthController@logout')->name('logout');
    Route::resource('companies', 'CompaniesController');
    Route::resource('employees', 'EmployeesController');
});

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input; 
use Illuminate\Support\Facades\Auth;

use App\Companies;
use App\Employees;

class CompaniesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Auth::check()){
            $companies = Companies::paginate(5);
            return view('companies.index', ['companies' => $companies]);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'nama'       => 'required',
            'email'      => 'required|email',
            'logo'      => 'required|mimes:png',
            'website' => 'required'
        ];
        $validator = Validator::make($request->all(), $rules);

        // process the login
        if ($validator->fails()) {
            return back()->with('alert', 'failed');
        } else {
            $nama = $request->nama;
            $email = $request->email;
            $logo = $request->file('logo');
            $logoname = $logo->getClientOriginalName();
            $website = $request->website;
    
            // Insert Companies data into table
            $result = Companies::insert([
                'nama' => $nama,
                'email' => $email,
                'logo' => $logoname,
                'website' => $website,
            ]);
            $logo->move(storage_path('app/company/'),$logoname);

            return back()->with('alert', 'success');
        }
        return back()->with('alert', 'failed');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $company = Companies::where('id', $id)->first();
        return view('companies.show', ['company' => $company]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'nama'       => 'required',
            'email'      => 'required|email',
            // 'logo'      => 'required|mimes:png',
            'filename' => 'required',
            'website' => 'required'
        ];
        $validator = Validator::make($request->all(), $rules);

        // process the login
        if ($validator->fails()) {
            return back()->with('alert', 'failed');
        } else {
            // store
            $logoname = '';
            if($request->file('logo')){
                $logo = $request->file('logo');
                $logoname = $logo->getClientOriginalName();
                $logo->move(storage_path('app/company/'),$logoname);
            }
            $company = Companies::find($id);
            $company->nama       = $request->nama;
            $company->email      = $request->email;
            $company->logo      = $logoname ? $logoname : $request->filename;
            $company->website = $request->website;
            $company->save();

            // redirect
            return back()->with('alert', 'success');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $any = Employees::where('company', $id)->first();
        if($any){
            return back()->with('alert', 'failed');
        }
        $company = Companies::where('id', $id)->delete();
        return back()->with('alert', 'success');
    }
}

resources/views/companies/create.blade.php
<html>
<head>
    <title>Add Company</title></head>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<body>
    @if(session()->has('alert'))
    @if(session()->get('alert') == 'success')
    <div class="alert alert-success">
        <strong>Success!</strong> Successfully!
    </div>
    @else
    <div class="alert alert-danger">
        <strong>Error!</strong> Gagal insert data company!
    </div>
    @endif
    @endif
    <a href="{{ route('companies.index') }}">Go to list data</a>
    <br/><br/>

    <form action="{{ route('companies.store') }}" method="POST" enctype="multipart/form-data" name="form1">
        @csrf
        <table width="50%" border="0">
            <tr> 
                <td>Nama</td>
                <td><input type="text" name="nama"></td>
            </tr>
            <tr> 
                <td>Email</td>
                <td><input type="text" name="email"></td>
            </tr>
            <tr> 
                <td>Logo</td>
                <td>
                    <br>
                    <input type="file" id="logo" name="logo" accept="image/png" onchange="" style="display:none">
                    <a href="#" class="btn btn-primary" onclick="browse()">Browse</a>
                    <p id="filename"></p>
                    <p id="size"></p>
                </td>
            </tr>
            <tr> 
                <td>Website</td>
                <td><input type="text" name="website"></td>
            </tr>
            <tr> 
                <td></td>
                <td><input type="submit" name="Submit" value="Add"></td>
            </tr>
        </table>
    </form>
</body>
</html>
<script> 
    var _URL = window.URL || window.webkitURL;
    $("#logo").change(function (e) {
        const fi = document.getElementById('logo'); 
        // Check if any file is selected. 
        if (fi.files.length > 0) { 
            for (let i = 0; i <= fi.files.length - 1; i++) { 
  
                const fsize = fi.files.item(i).size; 
                const file = Math.round((fsize / 1024)); 
                // The size of the file. 
                if (file > 2048) { 
                    alert("File too Big, please select a file less than 2mb"); 
                    fi.value = '';
                    document.getElementById('filename').innerHTML = '<b></b>';  
                    return;
                } 
            }  
            var file, img;
            if ((file = this.files[0])) {
                img = new Image();
                var objectUrl = _URL.createObjectURL(file);
                img.onload = function () {
                    if (this.width < 100 || this.height < 100) { 
                        alert("File too Small : "+this.width+"x"+this.height+"px, please select a file minimum 100x100 px"); 
                        fi.value = '';
                        document.getElementById('filename').innerHTML = '<b></b>';  
                        return;
                    } 
                    $filename = $('#logo').val();
                    $filename = $filename.split("\\")[2];
                    document.getElementById('filename').innerHTML = $filename; 
                    _URL.revokeObjectURL(objectUrl);
                };
                img.src = objectUrl;
            }
        } else {
            document.getElementById('filename').innerHTML = '<b></b>';  
            $('#filename').val(''); 
        }
    });
    function browse(){
        $('#logo').trigger('click');
    }
</script> 

resources/views/companies/index.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Companies</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;600&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            table {
                width:100%;
            }
            table, th, td {
                border: 1px solid black;
                border-collapse: collapse;
            }
            th, td {
                padding: 15px;
                text-align: left;
                color: black;
            }
            #t01 tr:nth-child(even) {
                background-color: #eee;
            }
            #t01 tr:nth-child(odd) {
                background-color: #fff;
            }
            #t01 th {
                background-color: grey;
                color: white;
            }
        </style>
    </head>
    <body>
    <div class="container">
        @if(session()->has('alert'))
        @if(session()->get('alert') == 'success')
        <div class="alert alert-success">
            <strong>Success!</strong> Success delete!
        </div>
        @else
        <div class="alert alert-danger">
            <strong>Error!</strong> Gagal delete, company digunakan sebagain foregin key data employees!
        </div>
        @endif
        @endif
        <h3>Data Companies</h3>
        <a href="{{ route('home') }}">Go To Dashboard</a><br/><br/>

        <a href="{{ route('companies.create') }}">Add New</a><br/><br/>
        <table style="width:100%;" id="t01">
            <tr>
                <th>Nama</th>
                <th>Email</th> 
                <th>Logo</th>
                <th>Website</th>
                <th>Aksi</th>
            </tr>
            
            <?php foreach ($companies as $company): ?>
                <tr>
                    <td><?php echo $company->nama; ?></td>
                    <td><?php echo $company->email; ?></td>
                    <td><?php echo $company->logo; ?></td>
                    <td><?php echo $company->website; ?></td>
                    <td>
                        <a href="{{route('companies.show', $company->id)}}" class="btn btn-info m-1">Edit</a>
                        <form action="{{ route('companies.destroy', $company->id) }}" method="POST">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <button class="btn btn-danger m-1">Delete</button>
                        </form>
                    </td>
                    <!-- <td><a href="{{ route('companies.show', $company->id) }}">Edit</a> | <a href="{{ route('companies.destroy', $company->id) }}">Delete</a></td> -->
                </tr>
            <?php endforeach; ?>
        </table>
        </div>

        <?php echo $companies->render(); ?>
    </body>
</html>

resources/views/companies/show.blade.php
<html>
<head>
    <title>Add Company</title></head>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<body>
    @if(session()->has('alert'))
    @if(session()->get('alert') == 'success')
    <div class="alert alert-success">
        <strong>Success!</strong> Successfully!
    </div>
    @else
    <div class="alert alert-danger">
        <strong>Error!</strong> Gagal update data company!
    </div>
    @endif
    @endif
    <a href="{{ route('companies.index') }}">Go to list data</a>
    <br/><br/>

    <form action="{{ route('companies.update', $company->id) }}" method="POST" enctype="multipart/form-data" name="form1">
        @csrf
        @method('PUT')
        <table width="50%" border="0">
            <tr> 
                <td>Nama</td>
                <td><input type="text" name="nama" value="{{ $company->nama }}"></td>
            </tr>
            <tr> 
                <td>Email</td>
                <td><input type="text" name="email" value="{{ $company->email }}"></td>
            </tr>
            <tr> 
                <td>Logo</td>
                <td>
                    <br>
                    <input type="file" id="logo" name="logo" accept="image/png" value=""  style="display:none">
                    <input type="hidden" id="filename" name="filename" accept="image/png" value="{{ $company->logo }}">
                    <a href="#" class="btn btn-primary" onclick="browse()">Browse</a>
                    <p id="filenametmp">{{ $company->logo }}</p>
                    <p id="size"></p>
                </td>
            </tr>
            <tr> 
                <td>Website</td>
                <td><input type="text" name="website" value="{{ $company->website }}"></td>
            </tr>
            <tr> 
                <td></td>
                <td><input type="submit" name="Submit" value="Update"></td>
            </tr>
        </table>
    </form>
</body>
</html>

<script> 
    var _URL = window.URL || window.webkitURL;
    $("#logo").change(function (e) {
        const fi = document.getElementById('logo'); 
        // Check if any file is selected. 
        if (fi.files.length > 0) { 
            for (let i = 0; i <= fi.files.length - 1; i++) { 
  
                const fsize = fi.files.item(i).size; 
                const file = Math.round((fsize / 1024)); 
                // The size of the file. 
                if (file > 2048) { 
                    alert("File too Big, please select a file less than 2mb"); 
                    fi.value = '';
                    document.getElementById('filenametmp').innerHTML = '<b></b>'; 
                    $('#filename').val(''); 
                    return;
                } 
            } 
            var file, img;
            if ((file = this.files[0])) {
                img = new Image();
                var objectUrl = _URL.createObjectURL(file);
                img.onload = function () {
                    if (this.width < 100 || this.height < 100) { 
                        alert("File too Small : "+this.width+"x"+this.height+"px, please select a file minimum 100x100 px"); 
                        fi.value = '';
                        document.getElementById('filenametmp').innerHTML = '<b></b>'; 
                        $('#filename').val(''); 
                        return;
                    } 
                    $filename = $('#logo').val();
                    $filename = $filename.split("\\")[2];
                    document.getElementById('filenametmp').innerHTML = $filename;
                    $('#filename').val($filename); 
                    _URL.revokeObjectURL(objectUrl);
                };
                img.src = objectUrl;
            }
        } else {
            document.getElementById('filenametmp').innerHTML = '<b></b>'; 
            $('#filename').val(''); 
        }
    });
    function browse(){
        $('#logo').trigger('click');
    }
</script> 