routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'AuthController@showFormLogin')->name('login');
Route::get('login', 'AuthController@showFormLogin')->name('login');
Route::post('login', 'AuthController@login');
Route::get('register', 'AuthController@showFormRegister')->name('register');
Route::post('register', 'AuthController@register');

Route::get('/soal1', function () {
    return view('soal1');
});
Route::group(['middleware' => 'auth'], function () {
    Route::get('home', function () {
        return view('welcome');
    })->name('home');
    Route::get('logout', 'AuthController@logout')->name('logout');
    Route::resource('companies', 'CompaniesController');
    Route::resource('employees', 'EmployeesController');
});

app/Employees.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employees extends Model
{
    protected $table = 'employees';
    protected $primaryKey = 'id';
    protected $foreignKey = 'company';

    public function companies()
    {
        return $this->belongsTo('App\Companies', 'company', 'id');
    }
}

app/Http/Controllers/EmployeesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input; 
use Illuminate\Support\Facades\Auth;

use App\Employees;
use App\Companies;

class EmployeesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Auth::check()){
            $employees = Employees::with('companies')->paginate(5);
            return view('employees.index', ['employees' => $employees]);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Companies::get();
        return view('employees.create', ['companies' => $companies]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'nama'       => 'required',
            'email'      => 'required|email',
            'company' => 'required'
        ];
        $validator = Validator::make($request->all(), $rules);

        // process the login
        if ($validator->fails()) {
            return back()->with('alert', 'failed');
        } else {
            $nama = $request->nama;
            $email = $request->email;
            $company = $request->company;
    
            // Insert Companies data into table
            $result = Employees::insert([
                'nama' => $nama,
                'company' => $company,
                'email' => $email
            ]);

            return back()->with('alert', 'success');
        }
        return back()->with('alert', 'failed');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $companies = Companies::get();
        $employee = Employees::where('id', $id)->first();
        return view('employees.show', ['employee' => $employee, 'companies' => $companies]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'nama'       => 'required',
            'company' => 'required',
            'email'      => 'required|email',
        ];
        $validator = Validator::make($request->all(), $rules);

        // process the login
        if ($validator->fails()) {
            return back()->with('alert', 'failed');
        } else {
            // store
            $company = Employees::find($id);
            $company->nama       = $request->nama;
            $company->company = $request->company;
            $company->email      = $request->email;
            $company->save();

            // redirect
            return back()->with('alert', 'success');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $company = Employees::where('id', $id)->delete();
        return back()->with('alert', 'success');
    }
}

resources/views/employees/create.blade.php
<html>
<head>
    <title>Add Company</title></head>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<body>
    @if(session()->has('alert'))
    @if(session()->get('alert') == 'success')
    <div class="alert alert-success">
        <strong>Success!</strong> Successfully!
    </div>
    @else
    <div class="alert alert-danger">
        <strong>Error!</strong> Gagal insert data employees!
    </div>
    @endif
    @endif
    <a href="{{ route('employees.index') }}">Go to list data</a>
    <br/><br/>

    <form action="{{ route('employees.store') }}" method="POST" enctype="multipart/form-data" name="form1">
        @csrf
        <table width="50%" border="0">
            <tr> 
                <td>Nama</td>
                <td><input type="text" name="nama"></td>
            </tr>
            <tr> 
                <td>Company</td>
                <td>
                    <select name="company">
                        <option value="" selected disabled>--Choose Company--</option>
                        <?php 
                            foreach($companies as $c){
                        ?>
                        <option value="{{ $c->id }}">{{ $c->nama }}</option>
                        <?php 
                            }
                        ?>
                    </select>
                </td>
            </tr>
            <tr> 
                <td>Email</td>
                <td><input type="text" name="email"></td>
            </tr>
            <tr> 
                <td></td>
                <td><input type="submit" name="Submit" value="Add"></td>
            </tr>
        </table>
    </form>
</body>
</html>
<script> 
</script> 

resources/views/employees/index.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Employees</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;600&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            table {
                width:100%;
            }
            table, th, td {
                border: 1px solid black;
                border-collapse: collapse;
            }
            th, td {
                padding: 15px;
                text-align: left;
                color: black;
            }
            #t01 tr:nth-child(even) {
                background-color: #eee;
            }
            #t01 tr:nth-child(odd) {
                background-color: #fff;
            }
            #t01 th {
                background-color: grey;
                color: white;
            }
        </style>
    </head>
    <body>
    <div class="container">
    @if(session()->has('alert'))
        @if(session()->get('alert') == 'success')
        <div class="alert alert-success">
            <strong>Success!</strong> Success delete!
        </div>
        @else
        <div class="alert alert-danger">
            <strong>Error!</strong> Gagal delete!
        </div>
        @endif
        @endif
        <h3>Data Employees</h3>
        <a href="{{ route('home') }}">Go To Dashboard</a><br/><br/>

        <a href="{{ route('employees.create') }}">Add New</a><br/><br/>
        <table style="width:100%;" id="t01">
            <tr>
                <th>Nama</th>
                <th>Company</th> 
                <th>Email</th>
                <th>Aksi</th>
            </tr>
            
            <?php foreach ($employees as $employee): ?>
                <tr>
                    <td><?php echo $employee->nama; ?></td>
                    <td><?php echo $employee->companies ? $employee->companies->nama : ''; ?></td>
                    <td><?php echo $employee->email; ?></td>
                    <td>
                        <a href="{{route('employees.show', $employee->id)}}" class="btn btn-info m-1">Edit</a>
                        <form action="{{ route('employees.destroy', $employee->id) }}" method="POST">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <button class="btn btn-danger m-1">Delete</button>
                        </form>
                    </td>
                    <!-- <td><a href="{{ route('employees.show', $employee->id) }}">Edit</a> | <a href="{{ route('employees.destroy', $employee->id) }}">Delete</a></td> -->
                </tr>
            <?php endforeach; ?>
        </table>
        </div>

        <?php echo $employees->render(); ?>
    </body>
</html>

resources/views/employees/show.blade.php
<html>
<head>
    <title>Add Company</title></head>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<body>
    @if(session()->has('alert'))
    @if(session()->get('alert') == 'success')
    <div class="alert alert-success">
        <strong>Success!</strong> Successfully!
    </div>
    @else
    <div class="alert alert-danger">
        <strong>Error!</strong> Gagal update data employee!
    </div>
    @endif
    @endif
    <a href="{{ route('employees.index') }}">Go to list data</a>
    <br/><br/>

    <form action="{{ route('employees.update', $employee->id) }}" method="POST" enctype="multipart/form-data" name="form1">
        @csrf
        @method('PUT')
        <table width="50%" border="0">
            <tr> 
                <td>Nama</td>
                <td><input type="text" name="nama" value="{{ $employee->nama }}"></td>
            </tr>
            <tr> 
                <td>Website</td>
                <td>
                    <select name="company">
                        <option value="" selected disabled>--Choose Company--</option>
                        <?php 
                            $selected = '';
                            foreach($companies as $c){
                                if($c->id == $employee->id){
                                    $selected = 'selected';
                                }
                        ?>
                        <option value="{{ $c->id }}" {{$selected}}>{{ $c->nama }}</option>
                        <?php 
                            }
                        ?>
                    </select>
                </td>
            </tr>
            <tr> 
                <td>Email</td>
                <td><input type="text" name="email" value="{{ $employee->email }}"></td>
            </tr>
            <tr> 
                <td></td>
                <td><input type="submit" name="Submit" value="Update"></td>
            </tr>
        </table>
    </form>
</body>
</html>

<script> 
</script> 